/* The following code was generated by JFlex 1.6.1 */

package br.edu.ifmg.bambui.ecomp.compiladores.jbasic;
import java.io.Reader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Scanner.jflex</tt>
 */
public class ScannerX {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\50\1\50\1\51\1\51\1\51\22\0\1\50\1\0\1\45"+
    "\1\0\1\25\5\0\1\6\1\3\1\0\1\5\1\4\1\0\12\1"+
    "\7\0\1\13\1\0\1\23\1\14\1\2\1\15\1\0\1\16\1\11"+
    "\2\0\1\20\1\24\1\17\1\22\2\0\1\10\1\21\1\12\2\0"+
    "\1\7\7\0\1\25\1\0\1\33\1\25\1\43\1\34\1\26\1\35"+
    "\1\25\1\36\1\31\2\25\1\40\1\44\1\37\1\42\2\25\1\30"+
    "\1\41\1\32\2\25\1\27\3\25\1\46\1\0\1\47\7\0\1\51"+
    "\252\0\2\11\115\0\1\21\u1ea8\0\1\51\1\51\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\14\1\14\3\2\1\1\4\4\0"+
    "\1\5\3\0\1\6\2\0\1\7\2\0\1\10\1\0"+
    "\1\11\2\0\1\12\1\0\4\3\1\6\2\3\1\7"+
    "\2\3\1\10\1\3\1\11\2\3\1\12\1\3\1\0"+
    "\1\13\1\0\1\2\1\0\1\5\1\2\4\0\1\14"+
    "\1\0\1\15\3\0\1\16\1\17\1\20\4\3\1\14"+
    "\1\3\1\15\3\3\1\16\1\17\1\20\1\21\1\22"+
    "\2\0\1\23\1\24\1\25\1\26\1\27\1\22\2\3"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\30"+
    "\1\31";

  private static int [] zzUnpackAction() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222\0\u024c\0\u0276"+
    "\0\u02a0\0\u02ca\0\u02f4\0\u031e\0\u0348\0\u0372\0\u039c\0\u03c6"+
    "\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2\0\u04ec\0\u0516"+
    "\0\u0540\0\u056a\0\250\0\u0594\0\u05be\0\u05e8\0\52\0\u0612"+
    "\0\u063c\0\52\0\u0666\0\u0690\0\u06ba\0\u06e4\0\52\0\u070e"+
    "\0\u0738\0\52\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\u0276"+
    "\0\u0834\0\u085e\0\u0276\0\u0888\0\u08b2\0\u08dc\0\u0906\0\u0276"+
    "\0\u0930\0\u095a\0\u0276\0\u0984\0\u046e\0\52\0\u09ae\0\52"+
    "\0\u09d8\0\u0a02\0\u0540\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\52"+
    "\0\u0ad4\0\52\0\u0afe\0\u0b28\0\u0b52\0\52\0\52\0\52"+
    "\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa\0\u0276\0\u0c24\0\u0276\0\u0c4e"+
    "\0\u0c78\0\u0ca2\0\u0276\0\u0276\0\u0276\0\52\0\52\0\u0ccc"+
    "\0\u0cf6\0\52\0\52\0\52\0\52\0\52\0\u0276\0\u0d20"+
    "\0\u0d4a\0\u0276\0\u0276\0\u0276\0\u0276\0\u0276\0\52\0\52"+
    "\0\u0276\0\u0276";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\2\1\5\1\2\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\2\1\15\2\2"+
    "\1\16\1\2\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\20\1\31\2\20\1\32"+
    "\1\20\1\33\1\34\1\35\1\2\1\36\54\0\1\3"+
    "\1\37\1\40\1\41\2\40\17\0\1\37\43\0\1\42"+
    "\17\0\1\42\12\0\1\43\60\0\1\44\5\0\1\45"+
    "\11\0\1\44\5\0\1\45\15\0\1\46\23\0\1\46"+
    "\40\0\1\47\1\0\1\50\15\0\1\47\1\0\1\50"+
    "\30\0\1\51\3\0\1\52\13\0\1\51\3\0\1\52"+
    "\26\0\1\53\17\0\1\53\14\0\1\54\17\0\1\55"+
    "\3\0\1\54\13\0\1\55\17\0\1\56\1\57\10\0"+
    "\1\60\5\0\1\56\1\57\10\0\1\60\31\0\1\61"+
    "\17\0\1\61\17\0\1\62\17\0\1\62\43\0\1\63"+
    "\17\0\1\63\10\0\1\20\23\0\20\20\6\0\1\20"+
    "\16\0\1\42\4\0\13\20\1\64\4\20\6\0\1\20"+
    "\6\0\1\44\5\0\1\45\6\0\3\20\1\65\5\20"+
    "\1\66\6\20\6\0\1\20\1\46\22\0\1\20\1\67"+
    "\16\20\6\0\1\20\13\0\1\47\1\0\1\50\5\0"+
    "\10\20\1\70\1\20\1\71\5\20\6\0\1\20\14\0"+
    "\1\51\3\0\1\52\2\0\11\20\1\72\3\20\1\73"+
    "\2\20\6\0\1\20\15\0\1\53\5\0\12\20\1\74"+
    "\5\20\6\0\1\20\1\54\17\0\1\55\2\0\1\20"+
    "\1\75\13\20\1\76\2\20\6\0\1\20\6\0\1\56"+
    "\1\57\10\0\1\60\2\0\3\20\1\77\1\100\10\20"+
    "\1\101\2\20\6\0\1\20\20\0\1\61\2\0\15\20"+
    "\1\102\2\20\6\0\1\20\6\0\1\62\14\0\3\20"+
    "\1\103\14\20\6\0\1\20\20\0\1\63\2\0\15\20"+
    "\1\104\2\20\5\0\45\105\1\106\4\105\47\107\1\0"+
    "\2\107\50\0\1\36\2\0\1\110\1\0\1\111\1\0"+
    "\1\111\45\0\1\112\51\0\1\113\71\0\1\114\17\0"+
    "\1\114\21\0\1\115\17\0\1\115\31\0\1\116\17\0"+
    "\1\116\33\0\1\117\17\0\1\117\30\0\1\120\17\0"+
    "\1\120\21\0\1\121\23\0\1\121\37\0\1\122\17\0"+
    "\1\122\40\0\1\123\17\0\1\123\25\0\1\124\17\0"+
    "\1\124\34\0\1\125\17\0\1\125\17\0\1\126\17\0"+
    "\1\126\33\0\1\127\17\0\1\127\33\0\1\130\17\0"+
    "\1\130\16\0\1\20\17\0\1\114\3\0\14\20\1\131"+
    "\3\20\6\0\1\20\7\0\1\115\13\0\4\20\1\132"+
    "\13\20\6\0\1\20\7\0\1\116\13\0\4\20\1\133"+
    "\13\20\6\0\1\20\11\0\1\117\11\0\6\20\1\134"+
    "\11\20\6\0\1\20\10\0\1\120\12\0\5\20\1\135"+
    "\12\20\6\0\1\20\1\121\22\0\1\20\1\136\16\20"+
    "\6\0\1\20\12\0\1\122\10\0\7\20\1\137\10\20"+
    "\6\0\1\20\21\0\1\123\1\0\16\20\1\140\1\20"+
    "\6\0\1\20\15\0\1\124\5\0\12\20\1\141\5\20"+
    "\6\0\1\20\20\0\1\125\2\0\15\20\1\142\2\20"+
    "\6\0\1\20\6\0\1\126\14\0\3\20\1\143\14\20"+
    "\6\0\1\20\10\0\1\127\12\0\5\20\1\144\12\20"+
    "\6\0\1\20\12\0\1\130\10\0\7\20\1\145\10\20"+
    "\5\0\47\107\1\146\2\107\1\0\1\110\51\0\1\112"+
    "\1\0\1\40\1\0\2\40\45\0\1\147\23\0\1\147"+
    "\35\0\1\150\17\0\1\150\37\0\1\151\17\0\1\151"+
    "\25\0\1\152\17\0\1\152\34\0\1\153\17\0\1\153"+
    "\32\0\1\154\17\0\1\154\13\0\1\155\23\0\1\155"+
    "\47\0\1\156\17\0\1\156\6\0\1\20\1\147\22\0"+
    "\1\20\1\157\16\20\6\0\1\20\10\0\1\150\12\0"+
    "\5\20\1\160\12\20\6\0\1\20\16\0\1\151\4\0"+
    "\13\20\1\161\4\20\6\0\1\20\12\0\1\152\10\0"+
    "\7\20\1\162\10\20\6\0\1\20\15\0\1\153\5\0"+
    "\12\20\1\163\5\20\6\0\1\20\16\0\1\154\4\0"+
    "\13\20\1\164\4\20\6\0\1\20\1\155\22\0\1\20"+
    "\1\165\16\20\6\0\1\20\22\0\1\156\17\20\1\166"+
    "\7\0\1\167\23\0\1\167\25\0\1\170\23\0\1\170"+
    "\24\0\1\20\1\167\22\0\1\20\1\171\16\20\6\0"+
    "\1\20\1\170\22\0\1\20\1\172\16\20\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3444];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\34\1\4\0\1\1\3\0\1\11\2\0"+
    "\1\11\2\0\1\1\1\0\1\11\2\0\1\11\1\0"+
    "\21\1\1\0\1\11\1\0\1\11\1\0\2\1\4\0"+
    "\1\11\1\0\1\11\3\0\3\11\15\1\2\11\2\0"+
    "\5\11\10\1\2\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

private ParserX parser;

public ScannerX(Reader reader, ParserX parser) {
    this(reader);
    this.parser = parser;
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScannerX(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 188) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return 0; }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return yytext().charAt(0);
            }
          case 26: break;
          case 2: 
            { parser.yylval = new Token(yyline,yytext());
    return ParserX.REAL;
            }
          case 27: break;
          case 3: 
            { parser.yylval = new Token(yyline,yytext());
    return ParserX.IDENTIFICADOR;
            }
          case 28: break;
          case 4: 
            { /* IGNORE */
            }
          case 29: break;
          case 5: 
            { parser.yylval = new Token(yyline,yytext());
    return ParserX.INT;
            }
          case 30: break;
          case 6: 
            { return ParserX.TK_IF;
            }
          case 31: break;
          case 7: 
            { return ParserX.TK_TO;
            }
          case 32: break;
          case 8: 
            { return ParserX.TK_DO;
            }
          case 33: break;
          case 9: 
            { return ParserX.TK_END_IF;
            }
          case 34: break;
          case 10: 
            { return ParserX.OR;
            }
          case 35: break;
          case 11: 
            { parser.yylval = new Token(yyline, yytext().substring(1,yytext().length()-1));
    return ParserX.STRING;
            }
          case 36: break;
          case 12: 
            { return ParserX.TK_INT;
            }
          case 37: break;
          case 13: 
            { return ParserX.AND;
            }
          case 38: break;
          case 14: 
            { return ParserX.TK_FOR;
            }
          case 39: break;
          case 15: 
            { return ParserX.NOT;
            }
          case 40: break;
          case 16: 
            { return ParserX.MOD;
            }
          case 41: break;
          case 17: 
            { /* IGNORAR OS COMENTARIOS */
            }
          case 42: break;
          case 18: 
            { return ParserX.TK_ELSE;
            }
          case 43: break;
          case 19: 
            { return ParserX.TK_READ;
            }
          case 44: break;
          case 20: 
            { return ParserX.TK_THEN;
            }
          case 45: break;
          case 21: 
            { return ParserX.TK_NEW_VAR;
            }
          case 46: break;
          case 22: 
            { return ParserX.TK_DONE;
            }
          case 47: break;
          case 23: 
            { return ParserX.TK_FROM;
            }
          case 48: break;
          case 24: 
            { return ParserX.TK_PRINT;
            }
          case 49: break;
          case 25: 
            { return ParserX.TK_WHILE;
            }
          case 50: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
