/* The following code was generated by JFlex 1.6.1 */

package br.edu.ifmg.bambui.ecomp.compiladores.jbasic;
import java.io.Reader;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>./Compiladores/Scanner.jflex</tt>
 */
public class ScannerX {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\46\1\46\1\47\1\47\1\47\22\0\1\46\1\0\1\43"+
    "\1\0\1\23\6\0\1\4\1\0\1\4\1\2\1\0\12\1\7\0"+
    "\1\11\1\0\1\21\1\12\1\3\1\13\1\0\1\14\1\7\2\0"+
    "\1\16\1\22\1\15\1\20\2\0\1\6\1\17\1\10\2\0\1\5"+
    "\7\0\1\23\1\0\1\31\1\23\1\41\1\32\1\24\1\33\1\23"+
    "\1\34\1\27\2\23\1\36\1\42\1\35\1\40\2\23\1\26\1\37"+
    "\1\30\2\23\1\25\3\23\1\44\1\0\1\45\7\0\1\47\252\0"+
    "\2\7\115\0\1\17\u1ea8\0\1\47\1\47\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\13\1\14\3\2\1\1\4\6\0"+
    "\1\5\2\0\1\6\2\0\1\7\1\0\1\10\2\0"+
    "\1\11\1\0\4\3\1\5\2\3\1\6\2\3\1\7"+
    "\1\3\1\10\2\3\1\11\1\3\1\0\1\12\1\0"+
    "\2\2\5\0\1\13\1\0\1\14\3\0\1\15\1\16"+
    "\1\17\4\3\1\13\1\3\1\14\3\3\1\15\1\16"+
    "\1\17\1\20\1\21\2\0\1\22\1\23\1\24\1\25"+
    "\1\26\1\21\2\3\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\27\1\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\310\0\360\0\u0118"+
    "\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258"+
    "\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\u0348\0\u0370\0\u0398"+
    "\0\u03c0\0\u03e8\0\u0410\0\u0438\0\u0460\0\u0488\0\u04b0\0\u04d8"+
    "\0\u0500\0\u0528\0\u0550\0\50\0\u0578\0\u05a0\0\50\0\u05c8"+
    "\0\u05f0\0\u0618\0\u0640\0\50\0\u0668\0\u0690\0\50\0\u06b8"+
    "\0\u06e0\0\u0708\0\u0730\0\u0758\0\u0230\0\u0780\0\u07a8\0\u0230"+
    "\0\u07d0\0\u07f8\0\u0820\0\u0848\0\u0230\0\u0870\0\u0898\0\u0230"+
    "\0\u08c0\0\u0410\0\50\0\u08e8\0\u0910\0\50\0\u0938\0\u0960"+
    "\0\u0988\0\u09b0\0\u09d8\0\50\0\u0a00\0\50\0\u0a28\0\u0a50"+
    "\0\u0a78\0\50\0\50\0\50\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18"+
    "\0\u0230\0\u0b40\0\u0230\0\u0b68\0\u0b90\0\u0bb8\0\u0230\0\u0230"+
    "\0\u0230\0\50\0\50\0\u0be0\0\u0c08\0\50\0\50\0\50"+
    "\0\50\0\50\0\u0230\0\u0c30\0\u0c58\0\u0230\0\u0230\0\u0230"+
    "\0\u0230\0\u0230\0\50\0\50\0\u0230\0\u0230";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\2\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\2\1\14\2\2\1\15"+
    "\1\2\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\17\1\30\2\17\1\31\1\17"+
    "\1\32\1\33\1\34\1\2\1\35\52\0\1\3\1\36"+
    "\1\37\20\0\1\37\41\0\1\40\17\0\1\40\17\0"+
    "\1\41\5\0\1\42\11\0\1\41\5\0\1\42\16\0"+
    "\1\43\20\0\1\43\36\0\1\44\1\0\1\45\15\0"+
    "\1\44\1\0\1\45\26\0\1\46\3\0\1\47\13\0"+
    "\1\46\3\0\1\47\24\0\1\50\17\0\1\50\15\0"+
    "\1\51\14\0\1\52\3\0\1\51\13\0\1\52\15\0"+
    "\1\53\1\54\10\0\1\55\5\0\1\53\1\54\10\0"+
    "\1\55\27\0\1\56\17\0\1\56\15\0\1\57\17\0"+
    "\1\57\41\0\1\60\17\0\1\60\10\0\1\17\21\0"+
    "\20\17\6\0\1\17\14\0\1\40\4\0\13\17\1\61"+
    "\4\17\6\0\1\17\4\0\1\41\5\0\1\42\6\0"+
    "\3\17\1\62\5\17\1\63\6\17\6\0\1\17\1\0"+
    "\1\43\17\0\1\17\1\64\16\17\6\0\1\17\11\0"+
    "\1\44\1\0\1\45\5\0\10\17\1\65\1\17\1\66"+
    "\5\17\6\0\1\17\12\0\1\46\3\0\1\47\2\0"+
    "\11\17\1\67\3\17\1\70\2\17\6\0\1\17\13\0"+
    "\1\50\5\0\12\17\1\71\5\17\6\0\1\17\1\0"+
    "\1\51\14\0\1\52\2\0\1\17\1\72\13\17\1\73"+
    "\2\17\6\0\1\17\4\0\1\53\1\54\10\0\1\55"+
    "\2\0\3\17\1\74\1\75\10\17\1\76\2\17\6\0"+
    "\1\17\16\0\1\56\2\0\15\17\1\77\2\17\6\0"+
    "\1\17\4\0\1\57\14\0\3\17\1\100\14\17\6\0"+
    "\1\17\16\0\1\60\2\0\15\17\1\101\2\17\5\0"+
    "\43\102\1\103\4\102\45\104\1\0\2\104\46\0\1\35"+
    "\2\0\1\105\47\0\1\106\2\0\1\107\62\0\1\110"+
    "\17\0\1\110\17\0\1\111\17\0\1\111\27\0\1\112"+
    "\17\0\1\112\31\0\1\113\17\0\1\113\26\0\1\114"+
    "\17\0\1\114\22\0\1\115\20\0\1\115\35\0\1\116"+
    "\17\0\1\116\36\0\1\117\17\0\1\117\23\0\1\120"+
    "\17\0\1\120\32\0\1\121\17\0\1\121\15\0\1\122"+
    "\17\0\1\122\31\0\1\123\17\0\1\123\31\0\1\124"+
    "\17\0\1\124\16\0\1\17\15\0\1\110\3\0\14\17"+
    "\1\125\3\17\6\0\1\17\5\0\1\111\13\0\4\17"+
    "\1\126\13\17\6\0\1\17\5\0\1\112\13\0\4\17"+
    "\1\127\13\17\6\0\1\17\7\0\1\113\11\0\6\17"+
    "\1\130\11\17\6\0\1\17\6\0\1\114\12\0\5\17"+
    "\1\131\12\17\6\0\1\17\1\0\1\115\17\0\1\17"+
    "\1\132\16\17\6\0\1\17\10\0\1\116\10\0\7\17"+
    "\1\133\10\17\6\0\1\17\17\0\1\117\1\0\16\17"+
    "\1\134\1\17\6\0\1\17\13\0\1\120\5\0\12\17"+
    "\1\135\5\17\6\0\1\17\16\0\1\121\2\0\15\17"+
    "\1\136\2\17\6\0\1\17\4\0\1\122\14\0\3\17"+
    "\1\137\14\17\6\0\1\17\6\0\1\123\12\0\5\17"+
    "\1\140\12\17\6\0\1\17\10\0\1\124\10\0\7\17"+
    "\1\141\10\17\5\0\45\104\1\142\2\104\1\0\1\105"+
    "\1\0\1\37\20\0\1\37\24\0\1\106\51\0\1\143"+
    "\20\0\1\143\33\0\1\144\17\0\1\144\35\0\1\145"+
    "\17\0\1\145\23\0\1\146\17\0\1\146\32\0\1\147"+
    "\17\0\1\147\30\0\1\150\17\0\1\150\14\0\1\151"+
    "\20\0\1\151\45\0\1\152\17\0\1\152\6\0\1\17"+
    "\1\0\1\143\17\0\1\17\1\153\16\17\6\0\1\17"+
    "\6\0\1\144\12\0\5\17\1\154\12\17\6\0\1\17"+
    "\14\0\1\145\4\0\13\17\1\155\4\17\6\0\1\17"+
    "\10\0\1\146\10\0\7\17\1\156\10\17\6\0\1\17"+
    "\13\0\1\147\5\0\12\17\1\157\5\17\6\0\1\17"+
    "\14\0\1\150\4\0\13\17\1\160\4\17\6\0\1\17"+
    "\1\0\1\151\17\0\1\17\1\161\16\17\6\0\1\17"+
    "\20\0\1\152\17\17\1\162\10\0\1\163\20\0\1\163"+
    "\26\0\1\164\20\0\1\164\24\0\1\17\1\0\1\163"+
    "\17\0\1\17\1\165\16\17\6\0\1\17\1\0\1\164"+
    "\17\0\1\17\1\166\16\17\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3200];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\33\1\6\0\1\11\2\0\1\11\2\0"+
    "\1\1\1\0\1\11\2\0\1\11\1\0\21\1\1\0"+
    "\1\11\1\0\1\1\1\11\5\0\1\11\1\0\1\11"+
    "\3\0\3\11\15\1\2\11\2\0\5\11\10\1\2\11"+
    "\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[118];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

private ParserX parser;

public ScannerX(Reader reader, ParserX parser) {
    this(reader);
    this.parser = parser;
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public ScannerX(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 186) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return 0; }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return yytext().charAt(0);
            }
          case 25: break;
          case 2: 
            { parser.yylval = new Token(yyline,yytext());
    return ParserX.NUMERO;
            }
          case 26: break;
          case 3: 
            { parser.yylval = new Token(yyline,yytext());
    return ParserX.IDENTIFICADOR;
            }
          case 27: break;
          case 4: 
            { /* IGNORE */
            }
          case 28: break;
          case 5: 
            { return ParserX.TK_IF;
            }
          case 29: break;
          case 6: 
            { return ParserX.TK_TO;
            }
          case 30: break;
          case 7: 
            { return ParserX.TK_DO;
            }
          case 31: break;
          case 8: 
            { return ParserX.TK_END_IF;
            }
          case 32: break;
          case 9: 
            { return ParserX.OR;
            }
          case 33: break;
          case 10: 
            { parser.yylval = new Token(yyline, yytext().substring(1,yytext().length()-1));
    return ParserX.STRING;
            }
          case 34: break;
          case 11: 
            { return ParserX.TK_INT;
            }
          case 35: break;
          case 12: 
            { return ParserX.AND;
            }
          case 36: break;
          case 13: 
            { return ParserX.TK_FOR;
            }
          case 37: break;
          case 14: 
            { return ParserX.NOT;
            }
          case 38: break;
          case 15: 
            { return ParserX.MOD;
            }
          case 39: break;
          case 16: 
            { /* IGNORAR OS COMENTARIOS */
            }
          case 40: break;
          case 17: 
            { return ParserX.TK_ELSE;
            }
          case 41: break;
          case 18: 
            { return ParserX.TK_READ;
            }
          case 42: break;
          case 19: 
            { return ParserX.TK_THEN;
            }
          case 43: break;
          case 20: 
            { return ParserX.TK_NEW_VAR;
            }
          case 44: break;
          case 21: 
            { return ParserX.TK_DONE;
            }
          case 45: break;
          case 22: 
            { return ParserX.TK_FROM;
            }
          case 46: break;
          case 23: 
            { return ParserX.TK_PRINT;
            }
          case 47: break;
          case 24: 
            { return ParserX.TK_WHILE;
            }
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
